FROM eclipse-temurin:21-jdk
#Information around who maintains the image
LABEL "org.opencontainers.image.authors"="fatma.com"
# Add the application's jar to the image
COPY target/teacher-0.0.1-SNAPSHOT.jar teacher-0.0.1-SNAPSHOT.jar
# execute the application
ENTRYPOINT ["java", "-jar", "teacher-0.0.1-SNAPSHOT.jar"]